### ISSUE TITLE
Adding wave radiation stress limiter

### ISSUE THREAD

**Issue by WPringle** [adcirc/adcirc#211]
Based on my ADCIRC+SWAN simulations I felt that it could be beneficial to have an upper limit on the wave radiation stresses to reduce instabilities (my ADCIRC only runs were never unstable, only the ADCIRC+SWAN runs were, and after some trial and error with an upper limit I was able to get a stable simulation). It is worth keeping in mind what the magnitude of the wave radiation stresses mean in terms of wind speeds.. So e.g., if they are equivalent to more than 50 m/s wind speed then perhaps there is something wrong with the size of the wave radiation stress.  

I added some lines in couple2swan.F (lines 412 & 413) to conduct the limiter on my GLOBAL branch which is under pull request #171. I have commented these out for now but perhaps we could implement this option through a namelist in future (namelist specifying the size of the upper limiter).  

What are you thoughts?

**Comment by zcobell** [comment]
Resolved by #383
