### ISSUE TITLE
Name conflict(s) between ADCIRC and WW3 (module constants)

### ISSUE THREAD

**Issue by pvelissariou1** [adcirc/adcirc#368]
**Describe the bug**
Coupled ADCIRC+WW3 executable fails to compile due to the name conflict of the "MODULE **CONSTANTS**" defined in both ADCIRC and WW3.

My suggestion is to rename "MODULE CONSTANTS" to "MODULE **ADC_CONSTANTS**" in src/constants.F90 and all occurences of "USE **CONSTANTS**" to "USE **ADC_CONSTANTS**".

**Comment by zcobell** [comment]
Fixed by #369
