### ISSUE TITLE
[BUG] leaky barrier test case with ibtype=25 not working with adcircv55.02 in parallel mode

### ISSUE THREAD

**Issue by tarankalra1** [adcirc/adcirc#374]
**Description of the bug**
- I am trying to model the test case that models internal boundary conditions with ibtype 24 and 25 with adcirc v55.02. If I have ibtype 24 and utilize `adcprep` to divide the domain, that works okay. Once I use ibtype = 25 for the internal boundary the adcprep throws an error. I attached a screenshot of the error. There is no issue when one runs this in serial mode. 

**To Reproduce**
Use the Internal overflow boundary test case that is distributed via dropbox. By default, all the ibtypes are set to 24. Replace last ibytpe = 25 to reproduce this issue. (https://adcirc.org/home/documentation/example-problems/internal-overflow-boundaries-example)

**Expected behavior**
adcprep execution steps fail for ibtype = 25 while work well for ibtype = 24 

**Screenshots**
Attached
![legacy_internal_overflow_case](https://github.com/adcirc/adcirc/assets/10886837/85053a34-c71b-4eff-b9be-efc39726a151)

**System (please complete the following information):**
 - OS: [Ubuntu 22.04]
 - Compiler: [GCC 11.4]
 - Version  [55.02].

**Comment by zcobell** [comment]
Thanks. I think this is just a question of making sure adcprep is treating the `ibtype=25` properly in its decomposition passes

**Comment by tarankalra1** [comment]
Thank you for getting to the issue. Yes, that is the gist of what I explained. Is there any support in fixing this bug ? Right now `ibtype=25` is not being treated properly in the distributed code.

**Comment by zcobell** [comment]
Hi @tarankalra1 - 

Please give this commit (bcb1e32264a4cb7b7ea0bfa1a2ce0ba17968ec27) a try. I think this resolves things, a pretty simple fix and we'll get this incorporated upstream assuming it also works on your end.
