### ISSUE TITLE
Inconsistent earth rotation speed when using Holland vortex model[BUG]

### ISSUE THREAD

**Issue by cblakely97** [adcirc/adcirc#377]
The subroutine HollandGet in wind.F defines its own value for the rotation speed of the earth (omega) as `omega = 2.0d0*pi / 86164.2d0`. This is not consistent with the value defined in constants.F of `omega = 7.29212d-5`. The values are different enough that test cases using the Holland vortex model (`NWS = 8`) do not pass when the maximum error is set to 0.00001. I have drafted a pull request to simply change the value used in HollandGet to use that defined in adc_constants.

**Comment by zcobell** [comment]
Sounds good. Please mark the pull request when it's ready
