### ISSUE TITLE
NWS19 don't work 

### ISSUE THREAD

**Issue by Jiangchao3** [adcirc/adcirc#397]
**Describe the bug**
Dear ADCIRC developer community, I am trying to run adcirc model for Irma (2017), using both NWS8, NWS19, NWS20 wind options, NWS8 and NWS20 works well, but NWS19 can run to the end, but seems the wind model is not activated, here I just show you the time series of windx and windy for some locations around coastal florida, Irma landfall there:
**NWS20**
![irma_wind_nws20](https://github.com/adcirc/adcirc/assets/66854878/04a64945-7a3f-41a5-9af3-94cbf08a116c)
**NWS19**
![irma_wind_nws19](https://github.com/adcirc/adcirc/assets/66854878/a4ee9e94-d629-4dc4-99eb-41534c0c0a25)

I also put my fort.22 and fort.15 file for the NWS19 run here, the fort.22 file is generated by ASWIP (./aswip -n 19 -m 2 -z 1),
[NWS19file.zip](https://github.com/user-attachments/files/15595448/NWS19file.zip)

**Discussion Topic**
I use the same way to run ASWIP to generate fort.22 for NWS20 run, no error exists, but failed for the NWS19 run, the fort.22 file seems reasonable according to the description on the adcirc website, and no error occur when I run the aswip code.

**System (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - Compiler: [e.g. GCC 13.1]
 - Version [e.g. 56]. Please include the version of ADCIRC, including the hash, as output from `./adcirc -v` or `./padcirc -v` and a descriptions of any code modifications you've made
 
I am not sure if it is my fault in some steps or the adcirc code have some errors exist cause the fault for running the NWS19. Could you please help have a look and give some suggestions about how to fix it. Many thanks.

Jiangchao

 -  -  -  - 
 -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -  -

**Comment by zcobell** [comment]
Hello @Jiangchao3 -

It is recommended to only use nws=20 and nws=19 will likely be removed in a future version

**Comment by Jiangchao3** [comment]
Hi @zcobell thanks for the response, good to know nws19 won't be used in future.

**Comment by Jiangchao3** [comment]
Hi @zcobell thanks for the response, good to know nws19 won't be used in future.
