### ISSUE TITLE
[BUG] 2 flags break things in 56.* for make-based building

### ISSUE THREAD

**Issue by wwlwpd** [adcirc/adcirc#408]
**Describe the bug**

So there are 2 problems:
1. `src/netcdf_error.F90` breaks on Intel with the -FI option; this file as a `.F90` was introduced into a directory full of `.F` files - I don't know the difference, but it is an inconsistency and breakage for people who maintain their own `work/cmplrflags.mk` file (not just ASGS)

2. `-fallow-argument-mismatch` as added to thirdparty/swan/macros.inc.gfortran that assumes gfortran >= 10, which is when it was added - this is _not_ a safe assumption

**Discussion Topic**
Is there a relevant topic from the discussion boards?

**To Reproduce**

Try to build 56.0.2 on a system using `gfortran` 9 (will break also for 5,6,7,8,9 - note: version 4 is broken due to not including IEEE intrinsics, but that version actual is _old_)

**Expected behavior**

ADCIRC should build, including `adcswan` and `padcswan`

**Screenshots**

**System (please complete the following information):**
 - OS: Ubuntu 22 (but really compiler issue)
 - Compiler: GCC 9 (likely down to 5)
 - Version 56.x (f7038e1f for the `thirdpart/swan/macros.inc.gfortran` issue)
 
**Additional context**
We account for this in our our ASGS build/patch system; but it might be affecting others particularly if they're running on local linux workstations, clusters, or via Windows WSL2

**Comment by zcobell** [comment]
Hi @wwlwpd - 

Good catch on the `-FI` flag. We will remove it from the `cmplrflags.mk` examples as any modern Intel-based compiler frontend sorts the source file format out on its own. If I had to guess, this was probably copied over a couple decades from a series of legacy compiler options.

As for the SWAN `macros.inc` question, I'm not sure there is much for us to do there as (a) those files come from the SWAN development team and (b) removing the flag makes the code not compile on gfortran >= 10. In this case, it seems like having the flag there for newer compilers (gfortran 10 is ~5 years old already) and allowing those with old compilers to remove it is probably best, so I'm guessing that was the SWAN team's decision here. For reference, I believe with the exception of OpenSUSE (which expires December 2024), all Linux distributions (Debian, RHEL, Ubuntu, CentOS, Fedora, etc) currently supported LTS versions no longer package GCC < 10 in their base image.

As always, both of these issues are all automatically handled within CMake, so hopefully folks will continue that migration so these issues do not arise as often any longer.

**Comment by wwlwpd** [comment]
Thank you @zcobell - do you happen to kno if SWAN is on github? They use a Perl script to decide what `macros.inc` to use, so maybe you're right this is better directed there. It should be pretty straightforward to differentiate between `gfortran` 9 and less or >= 10 as different compilers - which is what the SWAN's `platforms.pl` does. Thanks!

**Comment by wwlwpd** [comment]
Ok, I am still very willing to assist with maintaining the `make` infrastructure. So PLEASE reach out to me for anything related to that. This includes if/when you update SWAN in `thirdparty/swan`.
