### ISSUE TITLE
NetCDF error

### ISSUE THREAD

**Issue by uturuncoglu** [adcirc/adcirc#417]
**Describe the bug**
I was trying to update ADCIRC under UFS Coastal and running a regression test defined. the test fails with following error,

```
11: INFO: initializeMesh: THE NEIGHBOR TABLE IS BEING COMPUTED.
11: INFO: initializeMesh: THE NEIGHBOR TABLE IS COMPLETED. THE MINIMUM NUMBER OF NEIGHBORS FOR ANY NODE = 3. 1+THE MAXIMUM NUMBER OF NEIGHBORS FOR ANY NODE = 8. THE PARAMETER MNEI CAN BE SET AS SMALL AS 8.
11: ADCIRC Version is v56.0.1-12-gcce0472
11: ADCIRC Commit hash is cce0472f0f415bbf2334fd0cbb34f48b4d914781
11: ERROR: check_err: NetCDF: Invalid dimension ID or name
11: INFO: netcdfTerminate: ADCIRC Terminating.
```

As I know there were some change related with the netcdf output in the code and I wonder if there is any change required in the configuration file or do we need to add any extra variable to inputs. We might need to add some information to the NUOPC coupling interface but not sure. Any information could help at this point.

**Discussion Topic**
Is there a relevant topic from the discussion boards? N/A

**To Reproduce**
Please provide a minimum working example to trigger the behavior - this should be a relatively small problem (if possible) which can trigger the behavior

- checkout UFS Coastal
git clone --recursive https://github.com/oceanmodeling/ufs-weather-model.git
cd ufs-weather-model
cd ADCIRC-interface/ADCIRC
git fetch
git checkout v56.0.2
cd ../../tests
./rt.sh -l rt_coastal.conf -a nems -k -n "coastal_ike_shinnecock_atm2adc intel"

Note that this will only work on MSU Hercules machine since required input files are only available over there and also requires spack-stack installation. It also requires modification in CMake interface in the UFS Coastal level  since some new files are added to ADCIRC and they needs to be listed in the UFS Coastal level file.  Please let me know if you need that one.

**Expected behavior**
The model needs to run and pass the RT.

**Screenshots**
If applicable, add screenshots to help explain your problem. N/A

**System (please complete the following information):**
 - OS: [e.g. Ubuntu 22.04]
 - Compiler: [e.g. GCC 13.1] - Intel 2021.9.0
 - Version [e.g. 55.02]. Please include the version of ADCIRC, including the hash, as output from `./adcirc -v` or `./padcirc -v` and a descriptions of any code modifications you've made - tested with both v56.0.2 and main. 

**Additional context**
Add any other context about the problem here. N/A

**Comment by zcobell** [comment]
Hi @uturuncoglu -

Does this simulation use any files from older version of the model as input? For the major version change (v55-->v56) files like hot start files or output files that are written to/appended are not compatible. The simplest solution is to regenerate them. 

The change was necessary to correctly adhere to UGRID.

**Comment by uturuncoglu** [comment]
@zcobell Thanks for your help. Yes, we have fıles that are generated while back ago. Let me contact with the other Coastal team members and find out how we could generate those files. I'll keep you posted. BTW, it would be nice to get more informative error from the model since it does not indicate which file has issue and what is missing.

**Comment by zcobell** [comment]
Hi @uturuncoglu - I'm going to close this, but please re-open if this does not resolve your issue.

**Comment by uturuncoglu** [comment]
@zcobell Sorry for reopening this issue but I have one minor question. I generated most of the files but still failing. the only thing that I did not generate is the restart files. Is there any way to convert those restart files to be compatible with the newer version of code. If it is a simple change then maybe I could play with the exiting file to generate new one since I did not create those files and it would be hard for me to track it down.

**Comment by zcobell** [comment]
Hi @uturuncoglu - The restart files will need to be regenerated as well. I would take a look at the format [here](https://github.com/adcirc/adcirc-testsuite/blob/main/adcirc/adcirc_quarterannular-2d-netcdf-hotstart/01_cs/control/fort.67.nc). It should mostly amount to renaming a couple variables that made ADCIRC non-compliant with the UGRID standard. Hope that helps.

**Comment by zcobell** [comment]
Sounds good. Let me know how it all works out.
